<a href="https://colab.research.google.com/github/prachi-1804/ML_Practicals/blob/main/3rd_prac_5th_sem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
file='/content/wireless_signal_quality_dataset.csv'

data=pd.read_csv(file)

In [ ]:
print(data.head())

   Signal_Strength_dBm  SNR_dB  Interference_dB  Distance_m  Frequency_GHz  \
0                  -41       6                0         257            5.0   
1                  -86      25               20         134            2.4   
2                  -73      27                0         385            2.4   
3                  -57       5                0         255            5.0   
4                  -87      15               24          61            5.0   

   Channel_Bandwidth_MHz  Noise_Floor_dBm  Connected_Devices  \
0                    160             -100                 24   
1                    160              -96                 41   
2                     20              -72                 13   
3                    160              -86                  9   
4                     20              -79                 32   

   Estimated_Throughput_Mbps Quality  
0                         18    Poor  
1                         55    Poor  
2                         81 

In [ ]:
print(data.tail())

    Signal_Strength_dBm  SNR_dB  Interference_dB  Distance_m  Frequency_GHz  \
95                  -75      37               11          17            2.4   
96                  -88      11               18         231            5.0   
97                  -57       6               27         460            5.0   
98                  -49      25               24         298            2.4   
99                  -46       8               29         423            5.0   

    Channel_Bandwidth_MHz  Noise_Floor_dBm  Connected_Devices  \
95                    160              -80                 34   
96                     20              -90                 25   
97                    160              -76                 24   
98                     20              -78                 39   
99                     40              -71                 16   

    Estimated_Throughput_Mbps Quality  
95                        100    Fair  
96                         15    Poor  
97            

In [ ]:
print(data.isnull().sum())

Signal_Strength_dBm          0
SNR_dB                       0
Interference_dB              0
Distance_m                   0
Frequency_GHz                0
Channel_Bandwidth_MHz        0
Noise_Floor_dBm              0
Connected_Devices            0
Estimated_Throughput_Mbps    0
Quality                      0
dtype: int64


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Signal_Strength_dBm        100 non-null    int64  
 1   SNR_dB                     100 non-null    int64  
 2   Interference_dB            100 non-null    int64  
 3   Distance_m                 100 non-null    int64  
 4   Frequency_GHz              100 non-null    float64
 5   Channel_Bandwidth_MHz      100 non-null    int64  
 6   Noise_Floor_dBm            100 non-null    int64  
 7   Connected_Devices          100 non-null    int64  
 8   Estimated_Throughput_Mbps  100 non-null    int64  
 9   Quality                    100 non-null    object 
dtypes: float64(1), int64(8), object(1)
memory usage: 7.9+ KB


In [ ]:
data.describe()

,Signal_Strength_dBm,SNR_dB,Interference_dB,Distance_m,Frequency_GHz,Channel_Bandwidth_MHz,Noise_Floor_dBm,Connected_Devices,Estimated_Throughput_Mbps
count,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.00000,100.000000,100.000000
mean,-69.020000,21.150000,14.490000,264.500000,4.34400,64.200000,-84.80000,24.390000,49.590000
std,16.318162,10.641424,9.090449,136.653399,1.51866,46.562221,9.05427,14.537235,33.001713
min,-95.000000,5.000000,0.000000,17.000000,2.40000,20.000000,-100.00000,1.000000,1.000000
25%,-84.250000,11.750000,7.000000,158.750000,2.40000,20.000000,-93.25000,11.000000,22.750000
50%,-69.500000,19.500000,14.000000,270.500000,5.00000,40.000000,-84.50000,23.500000,49.000000
75%,-55.000000,31.000000,21.250000,370.500000,6.00000,80.000000,-76.00000,37.250000,78.250000
max,-40.000000,40.000000,30.000000,499.000000,6.00000,160.000000,-70.00000,50.000000,112.000000


In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder=LabelEncoder()
data['Quality']=label_encoder.fit_transform(data['Quality'])

In [ ]:
X =data.drop('Quality',axis=1)
Y=data['Quality']

In [ ]:
X=pd.get_dummies(X,drop_first=True)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import(
    accuracy_score,
    classification_report,
    confusion_matrix
)

train_test split


In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

 feature scaling


In [ ]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


 train logistic regression

In [ ]:

model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)


LogisticRegression(max_iter=1000)

Prediction

In [ ]:
y_pred=model.predict(X_test)

Evaluation

In [ ]:
print('/nAccuracy:')
print(accuracy_score(y_test,y_pred))

/nAccuracy:
0.65


In [ ]:
print('/nAccuracy matrix:')
print(confusion_matrix(y_test,y_pred))

/nAccuracy matrix:
[[0 0 1 0]
 [0 4 0 2]
 [0 2 1 0]
 [0 2 0 8]]


In [ ]:
print("\nClassification Report:")
print(classification_report(y_test,y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      0.67      0.57         6
           2       0.50      0.33      0.40         3
           3       0.80      0.80      0.80        10

    accuracy                           0.65        20
   macro avg       0.45      0.45      0.44        20
weighted avg       0.62      0.65      0.63        20



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
